bring back vimps1 that was retired in e1f9b31, clean up build process. ref #2
The use of -U_FORTIFY_SOURCE is for undefined symbols errors on xread and/or xgetcwd.

For Git, the captured child process doesn't work properly, the debug shows:

vcprompt: debug: spawning child process: git diff --no-ext-diff --quiet --exit-code
vcprompt: debug: child process git killed by signal 48
vcprompt: debug: spawning child process: git ls-files --others --exclude-standard
vcprompt: debug: child process git killed by signal 48

The modified and unknown states show correctly when the child process isn't killed with signal 48, according to kill -l, it's SIGRTMI+14.

Most of time, it's killed with the singal, few occasions that exiting properly.

See #2.

diff --git a/bin/Makefile b/bin/Makefile
--- a/bin/Makefile
+++ b/bin/Makefile
@@ -1,48 +1,43 @@
-CFLAGS += -g -O2
+CFLAGS   = -std=gnu99 -fPIC -g -O2 -Wall -Wextra
+CPPFLAGS = -U_FORTIFY_SOURCE \
+           -I/usr/include \
+           -I$(BASH_INCDIR) \
+           -I$(VCPROMPT_INCDIR) \
+           --include=/usr/include/getopt.h
+LDFLAGS  = -shared -Wl,-soname,$@
 
 ##########
 
-VIMPS1_CFLAGS = -fPIC -DHAVE_CONFIG_H -DSHELL ${CFLAGS}
-VIMPS1_LDFLAGS = -shared -Wl,-soname,$@ 
-
-BASH_TOPDIR = bash
-BASH_BUILDDIR = ${BASH_TOPDIR}
-BASH_INCDIR = ${BASH_TOPDIR}/include
-BASH_LIBBUILD = ${BASH_BUILDDIR}/lib
-BASH_INTLINC = 
+# Use Gentoo's path as default
+BASH_INCDIR = /usr/include/bash-plugins
 
 VCPROMPT_TOPDIR = vcprompt
-VCPROMPT_INCDIR = ${VCPROMPT_TOPDIR}
-VCPROMPT_SOURCES = $(wildcard $(VCPROMPT_TOPDIR)/*.c)
+VCPROMPT_INCDIR = ${VCPROMPT_TOPDIR}/src
+VCPROMPT_SOURCES = $(wildcard $(VCPROMPT_TOPDIR)/src/*.c)
 VCPROMPT_OBJECTS = $(addprefix $(VCPROMPT_TOPDIR).o/,$(notdir $(subst .c,.o,$(VCPROMPT_SOURCES))))
 
-VIMPS1_INC = -I. -I.. -I$(BASH_TOPDIR) -I$(BASH_TOPDIR)/lib -I$(BASH_TOPDIR)/builtins \
-      -I$(BASH_INCDIR) -I$(BASH_BUILDDIR) -I$(BASH_LIBBUILD) \
-      -I$(BASH_BUILDDIR)/builtins $(BASH_INTLINC) -I$(VCPROMPT_INCDIR) --include=/usr/include/getopt.h
+.PHONY: all
+all: CHECK_DIRS vimps1
 
-##########
-
-$(shell mkdir -p $(VCPROMPT_TOPDIR).o)
-
-all: vimps1
-
-##########
+.PHONY: CHECK_DIRS
+CHECK_DIRS:
+	@if ! test -f '$(BASH_INCDIR)'/builtins.h; then \
+	  echo 'error: cannot find Bash headers at $(BASH_INCDIR)' >&2; \
+	  echo 'maybe: $$ make BASH_INCDIR=/path/to/find/bash/builtins.h/at' >&2; \
+	  exit 1; \
+	fi
+	@if ! test -f '$(VCPROMPT_INCDIR)'/vcprompt.c; then \
+	  echo 'error: cannot find vcprompt sources at $(VCPROMPT_INCDIR)' >&2; \
+	  echo 'maybe: $$ hg clone http://hg.gerg.ca/vcprompt/' >&2; \
+	  exit 1; \
+	fi
+	mkdir -p $(VCPROMPT_TOPDIR).o
 
 vimps1: vimps1.o $(VCPROMPT_OBJECTS)
-	@echo $(VCPROMPT_OBJECTS)
-	$(CC) $(VIMPS1_LDFLAGS) -o $@ vimps1.o $(VCPROMPT_OBJECTS) $(LIBS)
-
-##########
 
 $(VCPROMPT_OBJECTS):
-	$(CC) -std=gnu99 $(VIMPS1_CFLAGS) $(CCFLAGS) $(VIMPS1_INC) -c -o $@ $(subst .o,,$(@:.o=.c))
+	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $(subst .o,/src,$(@:.o=.c))
 
-vimps1.o: vimps1.c
-	$(CC) $(VIMPS1_CFLAGS) $(CCFLAGS) $(VIMPS1_INC) -c -o $@ $<
-
-##########
-
+.PHONY: clean
 clean:
 	rm -f vimps1 vimps1.o $(VCPROMPT_OBJECTS)
-
-.PHONY: all clean
